--- 
cache: 
  directories: 
    - node_modules
deploy: 
  - 
    provider: script
    script: "chmod +x ./deploy.sh && ./deploy.sh"
    skip_cleanup: true
    true: 
      branch: master
install: 
  - "npm install"
language: node_js
node_js: 
  - "10"
script: 
  - "npm test"
services: mongodb